use_gpu: True
device: 0
seed: 1

early_stop:
    patience: 5

federate:
    mode: standalone
    method: 'decay'
    #local_update_steps: 1
    batch_or_epoch: batch
    total_round_num: 500
    client_num: 5
    unseen_clients_rate: 0.2

data:
    root: 'data/'
    type: 'pubmed'
    batch_size: 1
    splitter: 'louvain'
    num_workers: 0

model:
    type: gin
    hidden: 64
    dropout: 0.5
    out_channels: 5

optimizer:
    #lr: 0.25
    weight_decay: 0.0005

criterion:
    type: CrossEntropyLoss

trainer:
    type: nodefullbatch_trainer
    beta: 1.0

eval:
    freq: 5
    metrics: ['acc', 'correct', 'f1']
